exclude: .*[.](tsv|json|vtt)$
repos:
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v4.3.21
      hooks:
          - id: isort
    - repo: https://github.com/ambv/black
      rev: 19.10b0
      hooks:
          - id: black
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.1.0
      hooks:
          - id: check-byte-order-marker
          - id: check-json
          - id: check-yaml
          - id: detect-private-key
          - id: pretty-format-json
            args: ["--autofix", "--no-sort-keys", "--indent=4"]
          - id: mixed-line-ending
            args: ["--fix=lf"]
          - id: trailing-whitespace
    - repo: https://github.com/prettier/prettier
      rev: 2.0.5
      hooks:
          - id: prettier
            files: \.(css|less|scss|ts|tsx|graphql|gql|json|js|jsx|md)$
    - repo: https://github.com/awebdeveloper/pre-commit-stylelint
      rev: 0.0.2
      hooks:
          - id: stylelint
            additional_dependencies:
                - stylelint@13.6.0
                - stylelint-config-prettier@8.0.1
                - stylelint-config-recommended@3.0.0
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.3
      hooks:
          - id: flake8
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v7.2.0
      hooks:
          - id: eslint
            additional_dependencies:
                - eslint@7.2.0
                - eslint-plugin-prettier@3.1.3
                - prettier@2.0.5
                - eslint-plugin-unicorn@20.1.0
